Repository OCA/product-pack, pull requests merged in 2022-01, with the labels that each got.

#41 [FIX] stock_product_pack: stock on services packs
  stock_product_pack/models/product_product.py
Labels: approved, bot is merging ⏳, stale

#56 [14.0][MIG] sale_product_pack: migrate to 14.0
  sale_product_pack/README.rst
  sale_product_pack/__init__.py
  sale_product_pack/__manifest__.py
  sale_product_pack/demo/product_pack_line_demo.xml
  sale_product_pack/i18n/ca.po
  sale_product_pack/i18n/ca_ES.po
  sale_product_pack/i18n/es.po
  sale_product_pack/i18n/fr.po
  sale_product_pack/i18n/nl.po
  sale_product_pack/i18n/pt.po
  sale_product_pack/i18n/sale_product_pack.pot
  sale_product_pack/models/__init__.py
  sale_product_pack/models/product_pack_line.py
  sale_product_pack/models/sale_order.py
  sale_product_pack/models/sale_order_line.py
  sale_product_pack/readme/CONTRIBUTORS.rst
  sale_product_pack/readme/DESCRIPTION.rst
  sale_product_pack/readme/ROADMAP.rst
  sale_product_pack/readme/USAGE.rst
  sale_product_pack/security/ir.model.access.csv
  sale_product_pack/static/description/icon.png
  sale_product_pack/static/description/index.html
  sale_product_pack/tests/__init__.py
  sale_product_pack/tests/test_sale_product_pack.py
  sale_product_pack/views/product_pack_line_views.xml
  setup/sale_product_pack/odoo/addons/sale_product_pack
  setup/sale_product_pack/setup.py
Labels: bot is merging ⏳

#61 [14.0][IMP] product_pack: Change pack type to display type
  product_pack/models/product_template.py
Labels: enhancement, needs review, approved, bot is merging ⏳
