Repository OCA/product-pack, pull requests merged in 2024-10, with the labels that each got.

#182 [16.0][MIG] sale_stock_product_pack: Migration to 16.0
  sale_stock_product_pack/README.rst
  sale_stock_product_pack/__init__.py
  sale_stock_product_pack/__manifest__.py
  sale_stock_product_pack/i18n/it.po
  sale_stock_product_pack/i18n/sale_stock_product_pack.pot
  sale_stock_product_pack/models/__init__.py
  sale_stock_product_pack/models/sale_order.py
  sale_stock_product_pack/models/stock_move_line.py
  sale_stock_product_pack/readme/CONTRIBUTORS.rst
  sale_stock_product_pack/readme/DESCRIPTION.rst
  sale_stock_product_pack/readme/ROADMAP.rst
  sale_stock_product_pack/static/description/icon.png
  sale_stock_product_pack/static/description/index.html
  sale_stock_product_pack/tests/__init__.py
  sale_stock_product_pack/tests/test_sale_stock_product_pack.py
  setup/sale_stock_product_pack/odoo/addons/sale_stock_product_pack
  setup/sale_stock_product_pack/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#174 [17.0][MIG] website_sale_product_pack
  .eslintrc.yml
  website_sale_product_pack/README.rst
  website_sale_product_pack/__init__.py
  website_sale_product_pack/__manifest__.py
  website_sale_product_pack/i18n/it.po
  website_sale_product_pack/i18n/website_sale_product_pack.pot
  website_sale_product_pack/models/__init__.py
  website_sale_product_pack/models/product_product.py
  website_sale_product_pack/models/product_template.py
  website_sale_product_pack/models/sale_order.py
  website_sale_product_pack/models/website.py
  website_sale_product_pack/pyproject.toml
  website_sale_product_pack/readme/CONTRIBUTORS.md
  website_sale_product_pack/readme/DESCRIPTION.md
  website_sale_product_pack/readme/ROADMAP.md
  website_sale_product_pack/readme/USAGE.md
  website_sale_product_pack/static/description/icon.png
  website_sale_product_pack/static/description/index.html
  website_sale_product_pack/static/tests/tours/website_sale_product_pack_tour.js
  website_sale_product_pack/tests/__init__.py
  website_sale_product_pack/tests/test_website_sale_product_pack.py
  website_sale_product_pack/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#186 [16.0][FIX] sale_product_pack: Respect the order of the lines to be added
  sale_product_pack/models/sale_order_line.py
  sale_product_pack/tests/test_sale_product_pack.py
Labels: bot is merging ⏳
