Repository OCA/product-pack, pull requests merged in 2024-09, with the labels that each got.

#179 [16.0][FIX] sale_product_pack: Define the correct sequence of sale order lines
  sale_product_pack/models/product_pack_line.py
  sale_product_pack/models/sale_order_line.py
  sale_product_pack/tests/test_sale_product_pack.py
Labels: approved, bot is merging ⏳

#67 [14.0][ADD] pos_product_pack
  pos_product_pack/README.rst
  pos_product_pack/__init__.py
  pos_product_pack/__manifest__.py
  pos_product_pack/models/__init__.py
  pos_product_pack/models/pos_order_line.py
  pos_product_pack/readme/CONTRIBUTORS.rst
  pos_product_pack/readme/DESCRIPTION.rst
  pos_product_pack/readme/ROADMAP.rst
  pos_product_pack/readme/USAGE.rst
  pos_product_pack/static/description/icon.png
  pos_product_pack/static/description/index.html
  pos_product_pack/static/src/js/models.js
  pos_product_pack/views/pos_product_pack.xml
  setup/pos_product_pack/odoo/addons/pos_product_pack
  setup/pos_product_pack/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#183 Revert "[FIX] sale_product_pack: Define the correct sequence of sale order lines"
  sale_product_pack/models/product_pack_line.py
  sale_product_pack/models/sale_order_line.py
  sale_product_pack/tests/test_sale_product_pack.py
Labels: bot is merging ⏳
