Repository OCA/product-pack, pull requests merged in 2025-01, with the labels that each got.

#188 [17.0][MIG] stock_product_pack: Migration to 17.0
  stock_product_pack/README.rst
  stock_product_pack/__init__.py
  stock_product_pack/__manifest__.py
  stock_product_pack/i18n/es.po
  stock_product_pack/i18n/fr.po
  stock_product_pack/i18n/it.po
  stock_product_pack/i18n/pt.po
  stock_product_pack/i18n/stock_product_pack.pot
  stock_product_pack/models/__init__.py
  stock_product_pack/models/product_product.py
  stock_product_pack/models/product_template.py
  stock_product_pack/models/stock_rule.py
  stock_product_pack/pyproject.toml
  stock_product_pack/readme/CONTRIBUTORS.md
  stock_product_pack/readme/DESCRIPTION.md
  stock_product_pack/readme/USAGE.md
  stock_product_pack/security/ir.model.access.csv
  stock_product_pack/static/description/icon.png
  stock_product_pack/static/description/index.html
  stock_product_pack/tests/__init__.py
  stock_product_pack/tests/test_stock_product_pack.py
  stock_product_pack/views/product_template_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#198 [17][FIX]product_pack: args in _get_product_price/s methods
  product_pack/models/product_pricelist.py
Labels: bot is merging ⏳

#170 [MIG] sale_stock_product_pack: Migration to 17.0
  sale_stock_product_pack/README.rst
  sale_stock_product_pack/__init__.py
  sale_stock_product_pack/__manifest__.py
  sale_stock_product_pack/i18n/sale_stock_product_pack.pot
  sale_stock_product_pack/models/__init__.py
  sale_stock_product_pack/models/sale_order.py
  sale_stock_product_pack/pyproject.toml
  sale_stock_product_pack/readme/CONTRIBUTORS.md
  sale_stock_product_pack/readme/DESCRIPTION.md
  sale_stock_product_pack/readme/ROADMAP.md
  sale_stock_product_pack/static/description/icon.png
  sale_stock_product_pack/static/description/index.html
  sale_stock_product_pack/tests/__init__.py
  sale_stock_product_pack/tests/test_sale_stock_product_pack.py
Labels: approved, ready to merge, bot is merging ⏳

#189 [18.0][MIG] product_pack: Migration to 18.0
  product_pack/README.rst
  product_pack/__init__.py
  product_pack/__manifest__.py
  product_pack/demo/product_pack_line_demo.xml
  product_pack/demo/product_product_demo.xml
  product_pack/i18n/ca.po
  product_pack/i18n/de.po
  product_pack/i18n/es.po
  product_pack/i18n/fr.po
  product_pack/i18n/it.po
  product_pack/i18n/nl.po
  product_pack/i18n/product_pack.pot
  product_pack/i18n/pt.po
  product_pack/i18n/sv.po
  product_pack/models/__init__.py
  product_pack/models/product_pack_line.py
  product_pack/models/product_pricelist.py
  product_pack/models/product_product.py
  product_pack/models/product_template.py
  product_pack/pyproject.toml
  product_pack/readme/CONTRIBUTORS.md
  product_pack/readme/CONTRIBUTORS.rst
  product_pack/readme/ROADMAP.md
  product_pack/readme/ROADMAP.rst
  product_pack/readme/USAGE.md
  product_pack/readme/USAGE.rst
  product_pack/security/ir.model.access.csv
  product_pack/static/description/icon.png
  product_pack/static/description/index.html
  product_pack/tests/__init__.py
  product_pack/tests/common.py
  product_pack/tests/test_product_pack.py
  product_pack/views/product_pack_line_views.xml
  product_pack/views/product_product_views.xml
  product_pack/views/product_template_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#190 [18.0][MIG] sale_product_pack: Migration to 18
  sale_product_pack/README.rst
  sale_product_pack/__init__.py
  sale_product_pack/__manifest__.py
  sale_product_pack/demo/product_pack_line_demo.xml
  sale_product_pack/demo/sale_pack_demo.xml
  sale_product_pack/i18n/ca.po
  sale_product_pack/i18n/ca_ES.po
  sale_product_pack/i18n/es.po
  sale_product_pack/i18n/fr.po
  sale_product_pack/i18n/it.po
  sale_product_pack/i18n/nl.po
  sale_product_pack/i18n/pt.po
  sale_product_pack/i18n/sale_product_pack.pot
  sale_product_pack/models/__init__.py
  sale_product_pack/models/product_pack_line.py
  sale_product_pack/models/sale_order.py
  sale_product_pack/models/sale_order_line.py
  sale_product_pack/pyproject.toml
  sale_product_pack/readme/CONTRIBUTORS.md
  sale_product_pack/readme/DESCRIPTION.md
  sale_product_pack/readme/ROADMAP.md
  sale_product_pack/readme/USAGE.md
  sale_product_pack/security/ir.model.access.csv
  sale_product_pack/static/description/icon.png
  sale_product_pack/static/description/index.html
  sale_product_pack/tests/__init__.py
  sale_product_pack/tests/test_sale_product_pack.py
  sale_product_pack/views/product_pack_line_views.xml
Labels: needs review, migration, bot is merging ⏳

#201 [FIX] sale_product_pack: adjust discount formula for detailed packs
  sale_product_pack/models/sale_order_line.py
  sale_product_pack/tests/test_sale_product_pack.py
Labels: approved, bot is merging ⏳
